{% set version = "0.0.4" %}

package:
  name: epic2cf
  version: {{ version }}

source:
  fn: epic2cf-{{ version }}.tar.gz
  url: https://github.com/axiom-data-science/epic2cf/archive/{{ version }}.tar.gz
  sha256: 5fed51f0049cde6c3eddde193c5b549052e0314bb6d080c1f8b2d3cde3bde480

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - epic2cf

about:
  home: https://github.com/axiom-data-science/epic2cf
  license: MIT
  summary: 'A simple python library to find the CF standard name equivalent of an EPIC code.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
