travis:
  secure:
    BINSTAR_TOKEN: XuXr1eU7rI1gWk/x+yOONPKPwj9dbI7w/IO/WU3ILwIfhwgYDz3t74YmmPp1oZRLKvm/v4DZNiPtcYDIg0S/d+/KfQMjnDKBJVUIOb7fWsDGFLnNE7sk6ziaJKSfYmfcVHXo4xg3yi7j6FqjnnpmWuPbAvgmUflPKO2+C1K9tXuVqWW9iiIJymSh0dQeacU2Q52SLaETTQujVfdnYlfyrqEzg7z60ipCSgwfF83kOlo3MHohmj1Q3jFQCABipTcZVjxKL5lLPR0q3Sd7NjHGiwpcrcbykMqqaf8+QErKGngu497RmG1UylfgYThNainABwhbPd81iMOZ658LNyupXo7feHcJEDps2Eg+zkI2yks2z+VjVJ67YhHPMoDNu6lVGGO3I3MBJeD5RBbGfr2fmQVKqLRW+ms3MtAGZUYYoZU70SMpNSCkaegkurGVbOkX7vymqztc6rk/uP/V2mhJ7/X7sCODV6360XFmU2qZlloRqnlGELeLcK5weL058GPv9q6tIwuh3ab/npoeJp9VF2gWgBoCcc52hmPF6aHBmWmvCkhn/8F6VVFjRVzONf5dnwWDsnfVhb03ybqr43vq3F5/csyiJdbH1W+XB6KkVfKkiUUNbYBLZbaEpZKlGJFtpF+H3ylMdvU3SMt87iKRrPi9FPuEhZdQS+yGKeKtE9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
