travis:
  secure:
    BINSTAR_TOKEN: kgG/V9qKHU68mww5b9CCLdbfRKVQohJUtTvFImA5JzfiBVTz7iFESjDB5ZR5yOKlsTqqmdap1yyTFaTmTARVZ/UT+/Uo+/uf5npYfcxMsDZtKbpd7t+C1/w350NJm+WwkWTqcolQkG6/M2wrUOKfyX61D6m92i7phT9Hrio3rRaEh2Lh6RVbwBwIczdp+mnSZtNCySC6eeirEAfj+jEcFFMXmJtvMQtuzOOGgz1pl1RxNfoOfRr2OJGcd1wiQwq1DVZg2L3cdu90J62jTxCx9Dde0UVjdxY+m/TIWErNDvYxChUMv5qsxl2zLquUdYrgFz4gPQix4wsanldF7cKet3eHMbFCbhs9WxxcPa7/2PFNgjrvjazA74wFJTiPeU9wsiZE60KQv4ep2c+ZMhBeXWA9xRY9ZvHlAzzPw1I6iS5FLAAPl6ZuQ1om4m5gkJwLovYrDU3vSEuMyjCWc0OImMUWtHhjGb3sMFFXjP9driHvLX37zKe87sbyuRlJSkji3YxGFZdXRBjVWTLOBjKgrI8cKkw/O+QMmatRgXe9IN1JWX8Z0LAHmwMDq56LsnZiolGVL11IEAXpfIeqAeiAVWMno8iEZS57ITpVh4581C/NDu7Sdx5z9kfXCpTq3W1Az8QG+ZC48PTGG805b7wbSvDKNEW+Ey5//9chf5dPwGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
